language: javascript

install:
  - npm install -g eslint csslint uglify-es

script:
  - eslint src/*.js
  - csslint src/*.css

after_script:
  - uglifyjs src/callsign.js --compress --mangle
  - zip callsign.zip src/*

deploy:
  provider: releases
  api_key:
    secure: lkjnsdflnsdlkklsndflnsdflknsfdlkn
  file: "callsign.zip"
  skip_cleanup: true
  on:
    tags: true
