language: javascript
group: travis_latest

install:
  - npm install -g eslint csslint uglify-es csso-cli

script:
  - eslint src/*.js
  - csslint src/*.css

before_deploy:
  - uglifyjs src/callsign.js --compress passes=3,ecma=8 --mangle reserved=['cset'] --output callsign.min.js
  - csso src/callsign.css --output callsign.min.css
  - zip callsign.zip callsign.min.* src/*

deploy:
  provider: releases
  api_key:
    secure: lkjnsdflnsdlkklsndflnsdflknsfdlkn
  file: "callsign.zip"
  skip_cleanup: true
  on:
    tags: true
