name: CI
on: [push, pull_request]

jobs:
  test-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npx eslint src/

  build-jsdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./src
          output_dir: ./out
      - uses: actions/upload-artifact@v2
        with:
          name: jsdoc
          path: 'out/'
